services:
  postgres:
    image: postgres:13
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      retries: 10
      timeout: 3s
      interval: 5s
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=data
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth=md5
    # volumes:
    #   -postgres-db-volume:/var/lib/postgreql/data
    ports:
      - 5432:5432
    networks:
      - my_network
  
  app:
    build: .
    container_name: iarx_fast_api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/data
    ports:
      - 5000:5000
    volumes:
      - C:/Users/13042/Desktop/code/iArx_assessment/main.py:/opt/iarx/main.py
    command: >
      sh -c "python seed_data.py && uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    networks:
      - my_network
  
  cli:
    build:
      context: .
    command: >
      sh -c "python /opt/iarx/cli.py"
    volumes:
      - ./cli:/opt/cli
    depends_on:
      - app
    stdin_open: true  # Keep stdin open for interactive input
    tty: true         # Allocate a pseudo-TTY for interaction
    networks:
      - my_network

networks:
  my_network:
    driver: bridge