services:
  postgres:
    image: postgres:13
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      retries: 10
      timeout: 3s
      interval: 5s
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=data
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth=md5
    ports:
      - 5432:5432
    networks:
      - my_network
  
  app:
    build: ./api_code
    container_name: iarx_fast_api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/data
    ports:
      - 5000:5000
    command: >
      sh -c "python /opt/iarx/seed_data.py && uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - my_network
  
  cli:
    build:
      context: ./cli_code
    command: >
      sh -c "python /opt/iarx/cli.py"
    depends_on:
      app:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - my_network

networks:
  my_network:
    driver: bridge